openclaw:
  gateway_token: "testtoken"
  anthropic_api_key: ""
  gemini_api_key: ""
  additional_envs: []

llm:
  ollama_base_url: "http://192.168.1.100:11434"
  openai_api_base: ""
  openai_api_key: ""

network:
  gateway_port:
    bind_mode: published
    port_number: 18789
  bridge_port:
    bind_mode: published
    port_number: 18790

ix_volumes:
  config: /opt/tests/mnt/openclaw/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true

resources:
  limits:
    cpus: 2
    memory: 4096
