resources:
  limits:
    cpus: 2
    memory: 4096

onepassword:
  credentials: credentials

network:
  api_port:
    port_number: 8081
    bind_mode: published
  sync_port:
    port_number: 8082
    bind_mode: published

ix_volumes:
  data: /opt/tests/mnt/onepassword-connect/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
