images:
  image:
    repository: 1password/connect-api
    tag: 1.8.1
  sync_image:
    repository: 1password/connect-sync
    tag: 1.8.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  api_container_name: api
  sync_container_name: sync
  perms_container_name: permissions
  home_dir: /home/opuser/
  data_dir: /home/opuser/.op/data
  bus_port: 11223

  run_as_user: 999
  run_as_group: 999
