{% set tpl = ix_lib.base.render.Render(values) %}

{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.consts.run_as_user, "gid": values.consts.run_as_group, "mode": "check"} %}

{% set app = tpl.add_container(values.consts.openclaw_container_name, "image") %}
{% do app.set_user(values.consts.run_as_user, values.consts.run_as_group) %}
{% do app.set_init(true) %}

{% do app.healthcheck.set_test("curl", {"port": values.network.gateway_port.port_number, "path": "/"}) %}

{% do app.environment.add_env("HOME", "/home/node/.openclaw") %}
{% do app.environment.add_env("OPENCLAW_GATEWAY_BIND", "lan") %}
{% do app.environment.add_env("OPENCLAW_GATEWAY_TOKEN", values.openclaw.gateway_token) %}
{% if values.openclaw.anthropic_api_key %}
  {% do app.environment.add_env("ANTHROPIC_API_KEY", values.openclaw.anthropic_api_key) %}
{% endif %}
{% if values.openclaw.gemini_api_key %}
  {% do app.environment.add_env("GEMINI_API_KEY", values.openclaw.gemini_api_key) %}
{% endif %}

{% if values.llm.ollama_base_url %}
  {% do app.environment.add_env("OLLAMA_BASE_URL", values.llm.ollama_base_url) %}
{% endif %}
{% if values.llm.openai_api_base %}
  {% do app.environment.add_env("OPENAI_API_BASE", values.llm.openai_api_base) %}
{% endif %}
{% if values.llm.openai_api_key %}
  {% do app.environment.add_env("OPENAI_API_KEY", values.llm.openai_api_key) %}
{% endif %}

{% do app.environment.add_user_envs(values.openclaw.additional_envs) %}

{% do app.add_port(values.network.gateway_port) %}
{% do app.add_port(values.network.bridge_port) %}

{% do app.add_storage("/home/node/.openclaw", values.storage.config) %}

{% do app.set_command(["node", "openclaw.mjs", "gateway", "--allow-unconfigured", "--bind", "lan", "--port", values.network.gateway_port.port_number | string]) %}

{% do perm_container.add_or_skip_action("config", values.storage.config, perms_config) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do app.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.gateway_port) %}

{{ tpl.render() | tojson }}
