{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.gamevault_container_name, "gamevault_image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.gamevault.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.postgres_container_name, "postgres_image", pg_config, perm_container) %}

{% do c1.set_user(values.run_as.user, values.run_as.group) %}

{# Healthcheck #}
{% do c1.healthcheck.set_test("curl", {"port": values.network.web_port.port_number, "path": "/api/status"}) %}

{% do c1.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}

{# Environment Variables #}
{% do c1.environment.add_env("PUID", values.run_as.user) %}
{% do c1.environment.add_env("PGID", values.run_as.group) %}
{% do c1.environment.add_env("SERVER_ADMIN_USERNAME", values.gamevault.admin_username) %}
{% do c1.environment.add_env("SERVER_PORT", values.network.web_port.port_number) %}

{% do c1.environment.add_env("DB_HOST", values.consts.postgres_container_name) %}
{% do c1.environment.add_env("DB_USERNAME", values.consts.db_user) %}
{% do c1.environment.add_env("DB_PASSWORD", values.gamevault.db_password) %}
{% do c1.environment.add_env("DB_DATABASE", values.consts.db_name) %}

{% do c1.environment.add_user_envs(values.gamevault.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}

{# Storage #}
{% do c1.add_storage("/files", values.storage.files_storage) %}
{% do perm_container.add_or_skip_action("/files", values.storage.files_storage, perms_config) %}

{% do c1.add_storage("/media", values.storage.media_storage) %}
{% do perm_container.add_or_skip_action("/media", values.storage.media_storage, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
