images:
  image:
    repository: alpine/openclaw
    tag: "2026.2.15"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  openclaw_container_name: openclaw
  perms_container_name: permissions
  run_as_user: 568
  run_as_group: 568
