images:
  image:
    repository: alpine/openclaw
    tag: "2026.2.13"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  openclaw_container_name: openclaw
  perms_container_name: permissions
